SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS RIGHT OUTER JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE STRCMP(INS.SEX_UPON_INTAKE, OUTS.SEX_UPON_OUTCOME) != 0
ORDER BY INS.ANIMAL_ID