SELECT PRO.PRODUCT_CODE, SUM(PRO.PRICE * OFF.SALES_AMOUNT) AS SALES
FROM PRODUCT AS PRO
JOIN OFFLINE_SALE AS OFF
ON PRO.PRODUCT_ID = OFF.PRODUCT_ID
GROUP BY PRO.PRODUCT_CODE
ORDER BY SUM(PRO.PRICE * OFF.SALES_AMOUNT) DESC, PRO.PRODUCT_CODE