SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P 
    JOIN APPOINTMENT A ON P.PT_NO = A.PT_NO
    JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE A.MCDP_CD LIKE 'CS' AND DATEDIFF(A.APNT_YMD, '2022-04-13') = 0 AND A.APNT_CNCL_YMD IS NULL
ORDER BY A.APNT_YMD ASC