SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
    CASE 
    WHEN STATUS LIKE 'DONE' THEN '거래완료'
    WHEN STATUS LIKE 'RESERVED' THEN '예약중'
    WHEN STATUS LIKE 'SALE' THEN '판매중'
    END
    AS STATUS
FROM USED_GOODS_BOARD
WHERE DATEDIFF(CREATED_DATE, '2022-10-05') = 0
ORDER BY BOARD_ID DESC